export const API_ENDPOINT = {
  USERS: {
    LOGIN: "auth/login/cms",
    PROFILE: "auth/profile",
    SINGLE_ROLE:"portals/auth/single-role",
    COMPOSITE_ROLE:"portals/auth/composite-role",
    USER_GROUP:"portals/auth/user-group",
    CUSTOMER:"portals/users/customer",
    EMPLOYEE:"portals/users/employee",
    HOME_PAGE:"portals/content/homepage",
    PROMOTION:"portals/content/promotion",
    M_CUSTOMER:"portals/master-data/customer",
    M_SALE_EMP:"portals/master-data/sale-emp",
    M_MATERIAL:"portals/master-data/material",
    M_PRODUCTIMAGE:"portals/master-data/product-image",
    M_PRODECTGROUP:"portals/master-data/product-group",
    M_PRODECTGROUP_EXPORT:"portals/master-data/product-group/export/product-group",
    M_ASSIGNPROD:"portals/master-data/assign-prod-group-by-cust",
    ANNOUNCEMENT:"portal/delivery/bag-delivery-announcement",
    BAG_FORMULA_01:"portal/delivery/bag-delivery-formula01",
    BAG_FORMULA_02:"portal/delivery/bag-delivery-formula02",
    BAG_FORMULA_03:"portal/delivery/bag-delivery-formula03",
    BULK_FORMULA_01:"portal/delivery/bulk-delivery-formula01",
    DISTANCE:"portal/delivery/distance-master",
    MAPPING:"portal/delivery/mapping-zone",
    UPLOAD_ANNOUNCEMENT:"portal/delivery/import/announcement",
    UPLOAD_BAG_FORMULA_01:"portal/delivery/import/bag-formula01",
    UPLOAD_BAG_FORMULA_02:"portal/delivery/import/bag-formula02",
    UPLOAD_BAG_FORMULA_03:"portal/delivery/import/bag-formula03",
    UPLOAD_BULK_FORMULA_01:"portal/delivery/import/bulk-formula01",
    UPLOAD_DISTANCE_MASTER:"portal/delivery/import/distance-master",
    UPLOAD_MAPPING:"portal/delivery/import/mapping-zone",
    LOGOUT: "logout",
    CONSENT: "consentUser/action",
    COUTER: "counter",
    MAIN_SERVICE:"portals/service/main",
    SUB_SERVICE:"portals/service/sub",
    SERVICE:"portals/service",
    DROPDOWN:"portal/dropdown",
    SETTINGS:"portals/setting",
  },
  PORTAL:{
    TERM:"portals/security/termofuse",
    PRIVACY:"portals/security/privacy",
    LANGUAGE: "portals/setting"  // รอ service setting ใน backend
  },
  UPLOAD:{
    IMAGE_SERVICE:"file/public/upload",
    IMAGE_PRODUCT:"file/product-image/upload"
  },
  POPUP: {
    PRODUCT_IMAGE: "portals/master-data/product-image",
    TOU: "securities/termofuse",
    PRIVACY: "securities/privacy"
  },
  REPORT: { 
    CUSTOMER: "portals/report/customer-code",
    LAST2MONTHS: "portals/report/total/last2months",
    COMPARE_REPORT: "portals/report/amount/compare-report",
    TODAY_AMOUNT: "portals/report/today-amount",
    LAST_ORDER: "portals/report/last-orders",
    SERVICE_CHART: "portals/report/service",
    SERVICE_TABLE: "portals/report/service/list",
    TOP_MATERIAL_TABLE: "portals/report/top/material",
    TOP_CUSTOMER_TABLE: "portals/report/top/customer",
    TOP_MATERIAL_CHART: "portals/report/top/material/chart",
    TOP_CUSTOMER_CHART: "portals/report/top/customer/chart",
    DROPDOWN_BU: "portals/report/dropdown/bu",
    DROPDOWN_BRAND: "portals/report/dropdown/brand/",
    DROPDOWN_PRODUCT: "portals/report/dropdown/product/",
    PRODUCT_REPORT: "portals/report/top/material-in-brands",
    CUSTOMER_OPEN_TABLE: "portals/report/top/customer2",
    MAIN_SERVICE_LIST: "portals/report/dropdown/mainservice",
    SUB_SERVICE_LIST: "portals/report/dropdown/subservice/",
    STATISTIC_TABLE: "portals/report/request-service2",
    STATISTIC_DASHOBARD: "portals/report/request-service/chart2",
    STATISTIC_ORDER_DASHOBARD: "portals/report/order-transaction",
  },
  NOTIFICATION: { 
    LIST: "portals/notification",
    PUT: "portals/notification"
  }
};
