export const MESSAGE_TH = {
  1: "ค้นหาหมายเลขคำร้อง/สถานะ",
  2: "ค้นหาหมายเลขคำสั่งซื้อ/สถานะ",
  3: "วันที่ต้องการรับสินค้า",
  4: "วันที่ใบแจ้งหนี้",
  5: "วันที่คำร้อง",
  6: "วันที่ใบเสร็จ",
  7: "ค้นหาหมายเลขคำร้อง",
  8: "ค้นหาหมายเลขคำร้อง/หมายเลขคำสั่งซื้อ",
  9: "ค้นหาหมายเลขใบเสร็จ",
  10: "ขนาดไฟล์สูงสุด 50 MB",
  11: "ค้นหาหมายเลขคำสั่งซื้อ",
  12: "คุณมียอดค้างชำระ",
  13: "กรุณาตรวจสอบรายละเอียดในรายการใบแจ้งหนี้",
  14: "ไม่อนุญาตให้ใช้ประเภทไฟล์ที่คุณกำลังพยายามอัปโหลด (รองรับ: PNG, JPEG, JPG)",
  15: "ไม่อนุญาตให้ใช้ประเภทไฟล์ที่คุณกำลังพยายามอัปโหลด (รองรับ: MP4, MOV, FLV ,AVI, MKV)",
  16: "ค้นหาชื่อพนักงาน/รหัสพนักงาน/กลุ่ม User",
  17: "ค้นหาชื่อลูกค้า/รหัสลูกค้า",
  18: "ค้นหาชื่อโปรโมชั่น",
  19: "ค้นหาประเภทโปรโมชั่น/ชื่อโปรโมชั่น/กลุ่มธุรกิจ",
  20: "ค้นหารหัสลูกค้า/ชื่อลูกค้า/หมายเลขนิติบุคคล/หมายเลขบัตรประชาชน",
  21: "ค้นหารหัสพนักงานขาย/ชื่อ-นามสกุล",
  22: "ค้นหาสินค้า/ชื่อสินค้า/ชื่อทับศัพท์/คำอธิบายสินค้า",
  23: "ค้นหาชื่อไฟล์",
  24: "ค้นหาชื่อกลุ่มธุรกิจ(ไทย)(อังกฤษ) /ชื่อกลุ่มสินค้า(ไทย)(อังกฤษ) /ชื่อแบรนด์ (ไทย)(อังกฤษ)/ รหัสสินค้า",
};

export const MESSAGE_EN = {
  1: "Search request/status",
  2: "Search order number/status",
  3: "Date receive",
  4: "Invoice date",
  5: "Petition date",
  6: "Receipt date",
  7: "Search request number",
  8: "Search request number/Order number",
  9: "Search receipt number",
  10: "The specified file is larger than the maximum supported file size. (50MB)",
  11: "Search order number",
  12: "You have outstanding balance",
  13: "Please check the details in the invoice list.",
  14: "The file type you are attempting to upload is not allowed. (Support: PNG, JPEG, JPG)",
  15: "The file type you are attempting to upload is not allowed. (Support: MP4, MOV, FLV ,AVI, MKV)",
  16: "Search name/employee code/user group",
  17: "Search name/customer code",
  18: "Search promotion name",
  19: "Search promotion type/promotion name/business",
  20: "Search customer code/customer name/tax id/id card",
  21: "Search sales employee code/sales employee name",
  22: "Search material code/material description/sales name/long text",
  23: "Search file name ",
  24: "Search Business Unit Description (TH)(EN) /Product Group Description (TH)(EN) /Brand Description (TH)(EN) /Material Code",
};